name: Publish package to NPM
on:
  push:
    branches:
      - 'chore/gh-action-publish'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Show yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Pack
        run: yarn pack