name: Publish package to NPM
on:
  release:
    types:
      - "published"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Show yarn version
        run: yarn --version

      - name: Install dependencies
        run: yarn install

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Show version
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Update package.json
        run: yarn version ${{ env.RELEASE_VERSION }}

      - name: Build
        run: yarn build

  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish to NPM
        run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}